spring:
  mvc:
    view:
      #prefix: /WEB-INF/page/
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ljt?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root